MsgN(' ')
MsgN(' ')
MsgN('//////////////////////////////////')
MsgN('//   Loaded SHUD DarkRP Module  //')
MsgN('//       Version M-9 Stable     //')
MsgN('//////////////////////////////////')
MsgN(' ')
MsgN(' ')

CheckVersion()
